[package]
name = "tiltr"
version = "0.1.0"
authors = ["Kjell W. Kongsvik <kjell.kongsvik@gmail.com>"]
edition = "2018"

[dependencies]
rumble = "0.3.0"
rand = "0.7.2"
uuid = "0.4.0"
byteorder = "1.3.2"
