[package]
name = "tiltr"
version = "0.1.0"
authors = ["Kjell W. Kongsvik <kjell.kongsvik@gmail.com>"]
edition = "2018"

[dependencies]
btleplug = "0.4"
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
clap = "2"

