[package]
name = "tiltr"
version = "0.1.0"
authors = ["Kjell W. Kongsvik <kjell.kongsvik@gmail.com>"]
edition = "2018"

[dependencies]
rumble = "0.3"
serde = "1"
uuid = { version = "0.8", features = ["v4", "serde"] }
clap = "2"


[lib]
name = "tilt"
path = "src/tilt.rs"
