[package]
name = "tiltr"
version = "0.1.0"
authors = ["Kjell W. Kongsvik <kjell.kongsvik@gmail.com>"]
edition = "2018"

[dependencies]
rumble = "0.3"
rand = "0.7"
byteorder = "1"
mockito = "0.22"
reqwest = {version= "0.10", features = ["json"]}
serde = "1"
uuid = { version = "0.8", features = ["v4", "serde"] }
clap = "2"
url = "2"
futures-await-test = "0.3.0"
tokio = { version = "0.2", features = ["full"] }


[lib]
name = "tilt"
path = "src/tilt.rs"
