[package]
name = "tiltr"
version = "0.1.0"
authors = ["Kjell W. Kongsvik <kjell.kongsvik@gmail.com>"]
edition = "2018"

[dependencies]
rumble = "0.3"
rand = "0.7"
byteorder = "1.3"
mockito = "0.21"
reqwest = "0.9"
serde_json = "1.0"
serde = "1.0"
uuid = { version = "0.7", features = ["v4", "serde"] }
clap = "2"
url = "2"
